source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-remote-theme"
gem "jekyll-seo-tag"
gem "jekyll-include-cache"

# sass-embedded >= 1.65 treats mixed-unit interpolation as an error which
# breaks just-the-docs v0.10.x. Pin to the last compatible release.
gem "sass-embedded", "~> 1.63"

# Windows/JRuby compat stubs (harmless on Linux)
gem "webrick", "~> 1.8"
